FROM dolfinx/lab:stable
LABEL maintainer="Pierric Mora <pierric.mora@univ-eiffel.fr>"
LABEL description=" elastodynamics with Fenicsx/dolfinx "

WORKDIR /tmp
COPY . /tmp/
COPY ./examples /root/examples/

# Install elastodynamicsx and optional dependencies
RUN pip3 install . &&\
    pip3 install tqdm pyvista ipygany pythreejs ipyvtklink --upgrade &&\
    rm -rf /tmp/*

WORKDIR /root
