#FROM dolfinx/lab:v0.5.2
FROM dolfinx/lab:latest
LABEL maintainer="Pierric Mora <pierric.mora@univ-eiffel.fr>"
LABEL description=" elastodynamics with Fenicsx/dolfinx "

WORKDIR /tmp
COPY . /tmp/
COPY ./demo /root/demo/

# Install elastodynamicsx and optional dependencies
RUN pip3 install . &&\
    pip3 install tqdm pyvista ipygany pythreejs ipyvtklink --upgrade &&\
    rm -rf /tmp/*


######## install dolfinx_mpc #############
#https://github.com/jorgensd/dolfinx_mpc/blob/main/docker/Dockerfile

# This argument should be the same as what-ever the python version of the dol
ARG PYTHON_VERSION=3.10

# Clone DOLFINX_MPC source dir
RUN git clone https://github.com/jorgensd/dolfinx_mpc.git

# Install real mode
RUN . /usr/local/bin/dolfinx-real-mode && \
    . /usr/local/dolfinx-real/lib/dolfinx/dolfinx.conf && \
    cmake -G Ninja -DCMAKE_INSTALL_PREFIX=/usr/local/dolfinx-real  -DCMAKE_BUILD_TYPE=Developer -B build-dir-real dolfinx_mpc/cpp/ && \
    ninja install -j4  -C build-dir-real && \
    python3 -m pip install -v --target /usr/local/dolfinx-real/lib/python${PYTHON_VERSION}/dist-packages --no-dependencies --no-cache-dir dolfinx_mpc/python

# Clean repo to remove build dir from pip
RUN rm -rf dolfinx_mpc/python/build 

# Install complex mode
RUN . /usr/local/bin/dolfinx-complex-mode && \
    . /usr/local/dolfinx-complex/lib/dolfinx/dolfinx.conf && \
    cmake -G Ninja  -DCMAKE_INSTALL_PREFIX=/usr/local/dolfinx-complex -DCMAKE_BUILD_TYPE=Developer -B build-dir-complex dolfinx_mpc/cpp/ && \
    ninja install -j4  -C build-dir-complex && \
    python3 -m pip install -v --target /usr/local/dolfinx-complex/lib/python${PYTHON_VERSION}/dist-packages --no-dependencies --no-cache-dir dolfinx_mpc/python


WORKDIR /root
