# Configuration file for the Sphinx documentation builder.
#
# For the full list of built-in configuration values, see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Project information -----------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#project-information

import datetime, sys, os

import elastodynamicsx

sys.path.insert(0, os.path.abspath('..'))


# General information about the project.
project = 'ElastodynamiCSx'
now = datetime.datetime.now()
date = now.date()
copyright = f"{date.year}, Pierric Mora"
author = 'Pierric Mora'


# The short X.Y version.
version = elastodynamicsx.__version__
# The full version, including alpha/beta/rc tags.
release = elastodynamicsx.__version__


# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "en"


# -- General configuration ---------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#general-configuration

extensions = ["sphinx.ext.todo", "sphinx.ext.viewcode", "sphinx.ext.autodoc",
              'sphinx.ext.mathjax', 'sphinx.ext.ifconfig', 'sphinx.ext.napoleon',
              "myst_parser",
              'nbsphinx']

# myst-parser is used to manage (readme) markdown file
# ref : https://myst-parser.readthedocs.io/en/latest/syntax/optional.html
myst_enable_extensions = [
    "amsmath",
#    "attrs_inline",
#    "colon_fence",
#    "deflist",
    "dollarmath",   # to allow latex from markdown to be rendered in sphinx
#    "fieldlist",
#    "html_admonition",
#    "html_image",
#    "linkify",
#    "replacements",
#    "smartquotes",
#    "strikethrough",
#    "substitution",
#    "tasklist",
]

templates_path = ['_templates']
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']
autodoc_member_order = 'bysource'

# -- Options for HTML output -------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-html-output

html_theme = 'sphinx_rtd_theme'
# html_static_path = ['_static']
# html_logo = "logo.png"
html_theme_options = {
    # 'analytics_id': 'G-XXXXXXXXXX',  #  Provided by Google in your dashboard
    # 'analytics_anonymize_ip': False,
    # 'logo_only': True,
    # 'display_version': False,
    # 'prev_next_buttons_location': 'bottom',
    # 'style_external_links': False,
    # 'vcs_pageview_mode': '',
    # 'style_nav_header_background': 'white',
    # Toc options
    'collapse_navigation': False,
    'sticky_navigation': True,
    'navigation_depth': 3,
    'includehidden': True,
    'titles_only': False
    }


# -- Options for manual page output ---------------------------------------
napoleon_google_docstring = True
napoleon_use_admonition_for_notes = False
